# Generated by Django 4.2.2 on 2023-07-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registrationdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Password', models.CharField(blank=True, max_length=50, null=True)),
                ('Idd', models.ImageField(upload_to='Ids')),
                ('Photo', models.ImageField(upload_to='Photo')),
                ('Resume', models.ImageField(upload_to='Resume')),
            ],
        ),
    ]
