# Generated by Django 4.2.2 on 2023-07-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdb',
            name='Idd',
        ),
        migrations.RemoveField(
            model_name='registrationdb',
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='registrationdb',
            name='Resume',
        ),
        migrations.AddField(
            model_name='registrationdb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Images'),
        ),
    ]
