# Generated by Django 4.2.2 on 2023-07-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_remove_registrationdb_idd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdb',
            name='Resume',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
