# Generated by Django 4.2.2 on 2023-07-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_alter_registrationdb_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdb',
            name='Resume',
        ),
    ]
