# Generated by Django 4.1.7 on 2023-07-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0006_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='recipient',
        ),
    ]
