# Generated by Django 4.1.7 on 2023-07-24 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0007_rename_timestamp_message_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
