# Generated by Django 4.2.2 on 2023-07-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Frontend", "0008_delete_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leave_Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("username", models.CharField(blank=True, max_length=50, null=True)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Approved", "Approved")],
                        default="Pending",
                        max_length=20,
                    ),
                ),
            ],
        )
    ]
